Get new version in production
fhem/uba pull request #6
Opened 2020-01-24 23:38 UTC by florian-asche

2020-01-25 08:34 UTC, CoolTuxNet requested changes
Sieht soweit sehr gut aus. Ich habe noch eine Anmerkung gemacht in der Notify Sektion.
Ich würde noch versuchen ein error Reading ein zu bauen oder den state etwas zu ändern wenn eine fehlerhafte StationsID verwendet wird.

2020-01-25 08:34 UTC, LeonGaultier commented on FHEM/60_uba.pm
> +                                                or grep /^DELETEATTR.$name.interval$/,@{$events}
Hier fehlt noch ein Eintrag
grep /^MODIFIED.$name$/,@{$events}

2020-01-25 12:55 UTC, florian-asche commented
> Sieht soweit sehr gut aus. Ich habe noch eine Anmerkung gemacht in der Notify Sektion.
> Ich würde noch versuchen ein error Reading ein zu bauen oder den state etwas zu ändern wenn eine fehlerhafte StationsID verwendet wird.

Ich seh das nicht.

2020-01-25 13:25 UTC, LeonGaultier commented
Dann schreibe ich es hier. Dir fehlt noch eine REGEX auf MODIFY
grep /^MODIFIED.$name$/,@{$events}

2020-01-25 13:26 UTC, florian-asche commented
> Dann schreibe ich es hier. Dir fehlt noch eine REGEX auf MODIFY
> grep /^MODIFIED.$name$/,@{$events}

Achso, das habe ich schon korrigiert. Hast du eine Idee, wie ich am besten eine fehlerhafte StationID erkennen kann?

2020-01-25 13:39 UTC, florian-asche commented
Was mir noch aufgefallen ist, dass wenn die Daten geupdatet werden zunächst ein anders Datum haben und dass dann später auf das Datum aus dem JSON geändert wird. Kann man das ändern?

2020-01-25 13:53 UTC, LeonGaultier commented
Einen Fehlerhafte StationID könnte durch eine entsprechende API Antwort erkannt werden. Muss man sich mal anschauen.

Meinst Du mit Datum den Readings Readingstimestamp?

2020-01-25 15:45 UTC, florian-asche commented
> Einen Fehlerhafte StationID könnte durch eine entsprechende API Antwort erkannt werden. Muss man sich mal anschauen.
> 
> Meinst Du mit Datum den Readings Readingstimestamp?

Ja

2020-01-25 16:27 UTC, LeonGaultier commented
Kann ich Dir ehrlich gesagt gar nicht sagen.
Aber ich würde die ganzen readingsSingleUpdate zu readingsBulk umbauen. Dann kannst auch gleich IfChange verwenden. Also readingsBulkIfChanged

2020-01-25 17:30 UTC, florian-asche commented
> Kann ich Dir ehrlich gesagt gar nicht sagen.
> Aber ich würde die ganzen readingsSingleUpdate zu readingsBulk umbauen. Dann kannst auch gleich IfChange verwenden. Also readingsBulkIfChanged

Hast du ein anderes Module beim Namen, wo ich mir das ansehen kann?

2020-01-25 17:59 UTC, LeonGaultier commented
Ist jetzt nicht schwer

readingsBeginUpdate
readingsBulkUpdateIfChanged
readingsEndUpdate

2020-04-13 18:39 UTC, florian-asche commented
> 
> 
> Ist jetzt nicht schwer
> 
> readingsBeginUpdate
> readingsBulkUpdateIfChanged
> readingsEndUpdate

Habe ich jetzt umgestellt, das Verhalten hat sich aber leider nicht geändert.

2020-04-13 18:40 UTC, florian-asche commented
![image](https://user-images.githubusercontent.com/2785700/79149078-de03a980-7dc6-11ea-92c7-a88530830c0c.png)
und nach einem Reload 
![image](https://user-images.githubusercontent.com/2785700/79149106-e65be480-7dc6-11ea-9583-e89d674116c3.png)

Für die Simulation neuer Daten habe ich den Update Timestamp zurückgesetzt:
`setreading uba .lastUpdate 1586649600`

2020-04-13 18:59 UTC, christoph-morrison commented
Ich finde das Verhalten da von UBA auch nicht stringent zu dem Rest von FHEM. Der Timestamp des Readings ist ein Wert von **meinem** System, nicht vom UBA. Mach doch bitte lieber ein zusätzliches Reading mit i.e. `NO2_Timestamp` oder so, anstatt in meinem System am Timestamp rumzubasteln und das gerne auch nur dann, wenn `showTimeReadings` gesetzt ist. Ich kann's aber gerade nicht verifizieren, da ich keine Station mit Daten finde `¯\_(ツ)_/¯`

2020-04-13 22:14 UTC, florian-asche commented
https://forum.fhem.de/index.php/topic,47437.15.html?PHPSESSID=tghnbcq6c6av574k0mkjpbbi2p

2020-04-13 22:15 UTC, florian-asche commented
> 
> 
> Ich finde das Verhalten da von UBA auch nicht stringent zu dem Rest von FHEM. Der Timestamp des Readings ist ein Wert von **meinem** System, nicht vom UBA. Mach doch bitte lieber ein zusätzliches Reading mit i.e. `NO2_Timestamp` oder so, anstatt in meinem System am Timestamp rumzubasteln und das gerne auch nur dann, wenn `showTimeReadings` gesetzt ist. Ich kann's aber gerade nicht verifizieren, da ich keine Station mit Daten finde `¯\_(ツ)_/¯`

Ich will Daten nur mit einem Timestamp Datensatz. Wann das Update zuletzt lief wird im lastUpdate geschrieben.

2020-04-14 09:39 UTC, christoph-morrison commented
> Ich will Daten nur mit einem Timestamp Datensatz. Wann das Update zuletzt lief wird im lastUpdate geschrieben.

Das versteh ich nicht so ganz. Möchtest du, dass wenn z.B. ein NO2-Wert geliefert wird, dass der ReadingsTimestamp auf den Timestamp in den Daten gesetzt wird? Das fände ich ungewöhnlich.

2020-04-14 22:54 UTC, florian-asche commented
> > Ich will Daten nur mit einem Timestamp Datensatz. Wann das Update zuletzt lief wird im lastUpdate geschrieben.
> 
> Das versteh ich nicht so ganz: Möchtest du, dass wenn z.B. ein NO2-Wert geliefert wird, dass der ReadingsTimestamp auf den Timestamp in den Daten gesetzt wird? Das fände ich ungewöhnlich.

Das wurde u.a. in dem Module gebaut, damit auch Rückwirkend Daten importiert und noch mit dem normalen Plot so dargestellt werden können.

2020-05-02 13:15 UTC, florian-asche commented
Das Timestamp Problem beim Import wird unter #8 weiter gepflegt.

2020-05-02 13:15 UTC, florian-asche commented
ups

2020-05-02 13:15 UTC, merged

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +  $hash->{DefFn}        = "FHEM::uba::Define";
Hier bekommst du von Perl:Critic gleich wieder eine Watsche, kannst du auch einfach so schreiben:
```
$hash->{DefFn}        = \&Define;

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +sub Define($$$) {
Prototypen brauchst du hier nicht.

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +sub Initialize($) {
Prototypen brauchst du auch hier nicht ;-)

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +  InternalTimer( gettimeofday() + 60, "uba_GetUpdate", $hash);
Warum benutzt du hier `uba_GetUpdate` anstelle von `GetUpdate`?

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
>    return undef;
Perl::Critic!

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
>    my ($hash, @a) = @_;
`$a` ist eine magische Variable von Perl. Wäre ich vorsichtig mit.

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +      Log3 $name, 4, "-$i 0 component ID: ".$i;
Ich bin ganz davon weg, `Log3` für sowas zu verwenden. Ich hab mir in meinen eigenen Namespace eine Debugging-Funktion gelegt, die einerseits `Debug()` nutzt, andererseits aber ein Debug-Attribut berücksichtigt. So kannst du dann auch in Loglevel 1 loggen ohne dass du das Log des Users vollmüllst, wenn er ein niedriges Loglevel eingestellt hat.

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
>    $attribVal = "" if (!defined($attribVal));
Ich glaub `$attribVal` wird woanders gar nicht verwendet, oder?

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +sub DbLog_splitFn($) {
Der ganze `split`-Block is komisch, die Zuweisung könntest du auch direkt beim `split` machen.

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +      CO data (Kohlenstoffmonoxid) in µg/m³, 8h median value<br/>
carbon monoxide

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +      NO2 data (Stickstoffdioxid) in µg/m³, 1h median value<br/>
nitrogen dioxide

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +      O3 data (Ozon) in µg/m³, 1h median value<br/>
ozone

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +      PM10 data (Feinstaub) in µg/m³, 1h median value<br/>
fine dust pollution

2020-05-02 17:21 UTC, christoph-morrison commented on FHEM/60_uba.pm
> +      SO2 data (Schwefeldioxid) in µg/m³, 1h median value<br/>
Sulfur dioxide